version: '3.4'

services:
  dependency-injection-demo-client:
    container_name: "dependency-injection-demo"
    image: dependency-injection-demo.dll:latest
    environment:
      ASPNETCORE_ENVIRONMENT: docker
      ASPNETCORE_URLS: https://+:5000;http://+:5000;
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: ./dependency-injection-demo/Dockerfile